<?php

// Define a generator function that yields a range of integers from $from to $to.
function exampleGenerator(int $from = 1, int $to = 10): Iterator {
    // Loop through the range of numbers from $from to $to.
    for ($i = $from; $i <= $to; $i++) {
        yield $i;
    }
}

// Iterate through the values generated by exampleGenerator and display each value.
foreach (exampleGenerator() as $value) {
    echo " Value is " . $value;
}
echo '<br>';

// Define a generator function that yields key-value pairs.
function keyValueGenerators() {
    // Yield key-value pairs where keys are strings and values are fruit names.
    yield 'first' => 'apple';
    yield 'second' => 'banana';
    yield 'third' => 'mango';
}

// Iterate through the key-value pairs generated by keyValueGenerators and display them.
foreach (keyValueGenerators() as $key => $value) {
    echo $key . " : " . $value;
}
